# Generated by Django 2.0.2 on 2018-02-21 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendeeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee_title', models.CharField(choices=[('OWNERS', 'Owners'), ('MANAGERS', 'Managers'), ('EMPLOYEES', 'Employees'), ('DEPARTMENT', 'Deparment'), ('THIRD_PARTY', 'Third Party')], default='OWNERS', max_length=255)),
                ('is_department', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=255)),
                ('client_date', models.DateField()),
                ('logo_width', models.PositiveIntegerField()),
                ('logo_height', models.PositiveIntegerField()),
                ('logo_file', models.ImageField(height_field='logo_height', max_length=255, upload_to='uploads/company-logos/', width_field='logo_width')),
                ('year_end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('INFORMATION_TECHNOLOGY', 'Information Technology'), ('MANUFACTURING', 'Manufacturing'), ('SERVICE', 'Service'), ('RETAIL', 'Retail')], default='INFORMATION_TECHNOLOGY', max_length=255)),
                ('order', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('MARKETING', 'Marketing'), ('PRODUCT_DEVELOPMENT', 'Product Development'), ('MANUFACTURING', 'Manufacturing'), ('QUALITY_ASSURANCE', 'Quality Assurance'), ('SHIPPING', 'Shipping')], default='MARKETING', max_length=255)),
                ('order', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('start_date_time', models.DateTimeField()),
                ('end_date_time', models.DateTimeField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kro.Company')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('attendee_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kro.AttendeeType')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kro.Department')),
            ],
        ),
        migrations.CreateModel(
            name='ProvinceState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kro.Country')),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kro.MeetingType'),
        ),
        migrations.AddField(
            model_name='company',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kro.CompanyCategory'),
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kro.Country'),
        ),
        migrations.AddField(
            model_name='company',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kro.ProvinceState'),
        ),
    ]
