# Generated by Django 2.0.2 on 2018-02-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kro', '0002_auto_20180221_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendeetype',
            name='attendee_title',
            field=models.CharField(choices=[('OWNERS', 'Owners'), ('MANAGERS', 'Managers'), ('EMPLOYEES', 'Employees'), ('DEPARTMENT', 'Department'), ('THIRD_PARTY', 'Third Party')], default='OWNERS', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo_file',
            field=models.ImageField(height_field='logo_height', max_length=255, upload_to='uploads/company-logos/%Y/%m/%d/', width_field='logo_width'),
        ),
        migrations.AlterField(
            model_name='companycategory',
            name='order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='department',
            name='order',
            field=models.IntegerField(),
        ),
    ]
