# Generated by Django 2.0.2 on 2018-03-26 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kro', '0006_auto_20180315_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kro.Company')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kro.Department')),
            ],
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ADMINISTRATION', 'Administration'), ('SALES', 'Sales'), ('PRODUCTION', 'Production'), ('SERVICE', 'Service')], max_length=255)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('summary_of_position', models.TextField()),
                ('report_to', models.CharField(max_length=255)),
                ('administration', models.CharField(max_length=255)),
                ('nature_and_scope', models.CharField(max_length=255)),
                ('company_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kro.CompanyDepartment')),
                ('job_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kro.JobCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255)),
                ('is_owner', models.BooleanField()),
                ('is_manager', models.BooleanField()),
                ('is_employee', models.BooleanField()),
                ('is_third_party', models.BooleanField()),
                ('join_date', models.DateField()),
                ('position_date', models.DateField()),
                ('employee_number', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kro.Company')),
                ('job_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kro.JobDescription')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
