# Generated by Django 2.0.2 on 2018-03-28 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kro', '0008_auto_20180326_1557'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ATTENDEE', 'Attendee'), ('FACILITATOR', 'Facilitator'), ('CHAIR', 'Chair')], default='ATTENDEE', max_length=255)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kro.Meeting')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kro.Person')),
            ],
        ),
        migrations.AlterField(
            model_name='jobcategory',
            name='name',
            field=models.CharField(choices=[('ADMINISTRATION', 'Administration'), ('SALES', 'Sales'), ('PRODUCTION', 'Production'), ('SERVICE', 'Service')], default='ADMINISTRATION', max_length=255),
        ),
    ]
