# Generated by Django 2.0.2 on 2018-04-18 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kro', '0009_auto_20180328_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingProgressNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_notes', models.TextField()),
                ('post_meeting_notes', models.TextField()),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kro.Meeting')),
                ('presenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kro.Person')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kro.MeetingTopic')),
            ],
        ),
    ]
