# Generated by Django 2.0.2 on 2018-04-19 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kro', '0011_auto_20180418_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingParkingLot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('time_alloted', models.IntegerField()),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kro.Meeting')),
                ('meeting_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kro.MeetingSection')),
                ('meeting_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kro.MeetingTopic')),
                ('originator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kro.Person')),
            ],
        ),
    ]
