# Generated by Django 2.0.2 on 2018-04-19 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kro', '0012_meetingparkinglot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingparkinglot',
            name='meeting_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kro.MeetingSection'),
        ),
        migrations.AlterField(
            model_name='meetingparkinglot',
            name='meeting_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kro.MeetingTopic'),
        ),
    ]
