# Generated by Django 2.0.2 on 2018-04-20 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kro', '0013_auto_20180419_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowthClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('COMMUNICATION', 'Communication'), ('PROCESS', 'Process'), ('COMPETENCY', 'Competency')], default='COMMUNICATION', max_length=255)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Success',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('benefit_summary', models.TextField()),
                ('financial_success', models.BooleanField()),
                ('team_success', models.BooleanField()),
                ('brand_success', models.BooleanField()),
                ('individual_success', models.BooleanField()),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kro.Company')),
                ('growth_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kro.GrowthClass')),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kro.Meeting')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='success',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kro.Team'),
        ),
    ]
