# Generated by Django 2.0.2 on 2018-04-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kro', '0014_auto_20180420_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='success',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
