# Generated by Django 2.0.2 on 2018-04-27 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kro', '0017_auto_20180424_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_type', models.CharField(choices=[('PERSON', 'Person'), ('DEPARTMENT', 'Department'), ('EXTERNAL', 'External')], default='PERSON', max_length=255)),
                ('external_vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(max_length=255)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('company_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kro.CompanyDepartment')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kro.Person')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kro.Team')),
            ],
        ),
    ]
