# Generated by Django 2.0.2 on 2018-05-01 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kro', '0018_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('problem', models.TextField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('group_input', models.TextField()),
                ('financial_benefit', models.BooleanField()),
                ('team_benefit', models.BooleanField()),
                ('brand_benefit', models.BooleanField()),
                ('individual_benefit', models.BooleanField()),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kro.Company')),
                ('growth_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kro.GrowthClass')),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kro.Meeting')),
                ('originator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kro.Person')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kro.Team')),
            ],
        ),
    ]
