# Generated by Django 2.0.2 on 2018-05-02 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kro', '0020_auto_20180502_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMilestoneDevelopmentStepStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('percent_complete', models.IntegerField()),
                ('comments', models.TextField()),
                ('new_budget', models.IntegerField()),
                ('new_due_date', models.DateField()),
                ('growth_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kro.GrowthClass')),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kro.Meeting')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kro.Milestone')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kro.Project')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kro.Status')),
            ],
        ),
    ]
