# Generated by Django 2.0.2 on 2018-05-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kro', '0022_auto_20180502_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='estimated_budget',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='estimated_budget',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='projectmilestonedevelopmentstepstatus',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='projectmilestonedevelopmentstepstatus',
            name='new_budget',
            field=models.CharField(max_length=255),
        ),
    ]
