# Generated by Django 2.0.2 on 2018-05-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kro', '0023_auto_20180509_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='goals',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
