# Generated by Django 2.0.2 on 2018-05-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kro', '0024_auto_20180511_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmilestonedevelopmentstepstatus',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
