# Generated by Django 2.0.2 on 2018-05-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kro', '0025_auto_20180516_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
