# Generated by Django 2.0.2 on 2018-05-31 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kro', '0026_auto_20180527_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
