# Generated by Django 2.0.2 on 2018-06-06 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kro', '0027_auto_20180531_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentRequestPersons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField()),
                ('assessed_by_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kro.Person')),
            ],
        ),
        migrations.CreateModel(
            name='StrengthAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateTimeField(auto_now_add=True)),
                ('assessment_start_time', models.DateTimeField()),
                ('assessment_end_time', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('development_skill', models.IntegerField()),
                ('development_knowledge', models.IntegerField()),
                ('development_passion', models.IntegerField()),
                ('development_wisdom', models.IntegerField()),
                ('employee_additional_comments', models.TextField()),
                ('assessed_by_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kro.Person')),
            ],
        ),
        migrations.CreateModel(
            name='StrengthAssessmentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('review_period_from', models.DateTimeField(auto_now_add=True)),
                ('review_period_to', models.DateTimeField(auto_now_add=True)),
                ('person_assessed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kro.Person')),
            ],
        ),
        migrations.CreateModel(
            name='StrengthAssessmentReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('reviewers_comments', models.TextField()),
                ('employee_comments', models.TextField()),
                ('assessed_by_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kro.Person')),
                ('assessment_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kro.StrengthAssessmentRequest')),
            ],
        ),
        migrations.CreateModel(
            name='StrengthAssessmentValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_score', models.IntegerField()),
                ('order', models.IntegerField()),
                ('strength_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kro.StrengthAssessment')),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_type', models.CharField(choices=[('FINANCIAL', 'Financial'), ('TEAM', 'Team'), ('BRAND', 'Brand')], default='FINANCIAL', max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('statement', models.CharField(max_length=255)),
                ('order', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kro.Company')),
            ],
        ),
        migrations.AddField(
            model_name='strengthassessmentvalue',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kro.Value'),
        ),
        migrations.AddField(
            model_name='strengthassessment',
            name='assessment_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kro.StrengthAssessmentRequest'),
        ),
        migrations.AddField(
            model_name='assessmentrequestpersons',
            name='strength_assessment_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kro.StrengthAssessmentRequest'),
        ),
    ]
