# Generated by Django 2.0.2 on 2018-06-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kro', '0028_auto_20180606_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strengthassessmentrequest',
            name='review_period_from',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='strengthassessmentrequest',
            name='review_period_to',
            field=models.DateTimeField(),
        ),
    ]
