# Generated by Django 2.0.2 on 2018-06-06 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kro', '0029_auto_20180606_1405'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssessmentRequestPersons',
            new_name='AssessmentRequestPerson',
        ),
    ]
