# Generated by Django 2.0.2 on 2018-06-13 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kro', '0030_auto_20180606_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strengthassessment',
            name='location',
        ),
    ]
