# Generated by Django 2.0.2 on 2018-06-29 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kro', '0032_strengthassessmentrequest_randomize_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_appraisal', models.DateTimeField()),
                ('review_period_from', models.DateTimeField()),
                ('review_period_to', models.DateTimeField()),
                ('overall_performance', models.TextField()),
                ('strengths', models.TextField()),
                ('areas_for_further_developemnt', models.TextField()),
                ('challenges', models.TextField()),
                ('employee_comments', models.TextField()),
                ('person_reviewed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='kro.Person')),
                ('reviewed_by_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='kro.Person')),
            ],
        ),
    ]
