# Generated by Django 2.0.2 on 2018-07-04 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kro', '0033_performancereview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performancereview',
            old_name='areas_for_further_developemnt',
            new_name='areas_for_further_development',
        ),
    ]
