# Generated by Django 2.0.2 on 2018-07-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kro', '0034_auto_20180704_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancereview',
            name='date_of_appraisal',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
