# Generated by Django 2.0.2 on 2018-07-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kro', '0037_auto_20180716_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='picture_file',
            field=models.ImageField(blank=True, height_field='picture_height', max_length=255, null=True, upload_to='uploads/profile-picture/%Y/%m/%d/', width_field='picture_width'),
        ),
    ]
