# Generated by Django 2.0.2 on 2018-07-16 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kro', '0038_auto_20180716_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmilestonedevelopmentstepstatus',
            name='growth_class',
        ),
    ]
