# Generated by Django 2.0.2 on 2018-07-18 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kro', '0039_remove_projectmilestonedevelopmentstepstatus_growth_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='strengthassessmentreview',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='strengthassessmentreview',
            name='employee_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strengthassessmentreview',
            name='reviewers_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
