# Generated by Django 2.0.2 on 2018-07-18 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kro', '0041_auto_20180718_1022'),
        ('kro', '0040_auto_20180718_1335'),
    ]

    operations = [
    ]
