# Generated by Django 2.0.2 on 2018-07-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kro', '0042_merge_20180718_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancereview',
            name='areas_for_further_development',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='challenges',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='employee_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='overall_performance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='strengths',
            field=models.TextField(blank=True, null=True),
        ),
    ]
