# Generated by Django 2.0.2 on 2018-07-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kro', '0043_auto_20180718_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedevelopmentplanreview',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
